/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../../routes/__root'
import { Route as LandingImport } from './../../routes/_landing'
import { Route as HomeImport } from './../../routes/_home'
import { Route as AuthImport } from './../../routes/_auth'
import { Route as LandingIndexImport } from './../../routes/_landing.index'
import { Route as LandingPricingImport } from './../../routes/_landing.pricing'
import { Route as LandingDemoImport } from './../../routes/_landing.demo'
import { Route as HomeResumeImport } from './../../routes/_home.resume'
import { Route as HomeApplicationsImport } from './../../routes/_home.applications'
import { Route as HomeAnalyticsImport } from './../../routes/_home.analytics'
import { Route as DebugHealthcheckImport } from './../../routes/_debug.healthcheck'
import { Route as AuthOnboardImport } from './../../routes/_auth.onboard'
import { Route as HomeJobsIndexImport } from './../../routes/_home.jobs.index'
import { Route as HomeResumeIdImport } from './../../routes/_home.resume.$id'
import { Route as HomeApplicationsTableImport } from './../../routes/_home.applications.table'
import { Route as HomeApplicationsKanbanImport } from './../../routes/_home.applications.kanban'

// Create/Update Routes

const LandingRoute = LandingImport.update({
  id: '/_landing',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LandingIndexRoute = LandingIndexImport.update({
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)

const LandingPricingRoute = LandingPricingImport.update({
  path: '/pricing',
  getParentRoute: () => LandingRoute,
} as any)

const LandingDemoRoute = LandingDemoImport.update({
  path: '/demo',
  getParentRoute: () => LandingRoute,
} as any)

const HomeResumeRoute = HomeResumeImport.update({
  path: '/resume',
  getParentRoute: () => HomeRoute,
} as any)

const HomeApplicationsRoute = HomeApplicationsImport.update({
  path: '/applications',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAnalyticsRoute = HomeAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => HomeRoute,
} as any)

const DebugHealthcheckRoute = DebugHealthcheckImport.update({
  path: '/healthcheck',
  getParentRoute: () => rootRoute,
} as any)

const AuthOnboardRoute = AuthOnboardImport.update({
  path: '/onboard',
  getParentRoute: () => AuthRoute,
} as any)

const HomeJobsIndexRoute = HomeJobsIndexImport.update({
  path: '/jobs/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeResumeIdRoute = HomeResumeIdImport.update({
  path: '/$id',
  getParentRoute: () => HomeResumeRoute,
} as any)

const HomeApplicationsTableRoute = HomeApplicationsTableImport.update({
  path: '/table',
  getParentRoute: () => HomeApplicationsRoute,
} as any)

const HomeApplicationsKanbanRoute = HomeApplicationsKanbanImport.update({
  path: '/kanban',
  getParentRoute: () => HomeApplicationsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_landing': {
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/_auth/onboard': {
      preLoaderRoute: typeof AuthOnboardImport
      parentRoute: typeof AuthImport
    }
    '/_debug/healthcheck': {
      preLoaderRoute: typeof DebugHealthcheckImport
      parentRoute: typeof rootRoute
    }
    '/_home/analytics': {
      preLoaderRoute: typeof HomeAnalyticsImport
      parentRoute: typeof HomeImport
    }
    '/_home/applications': {
      preLoaderRoute: typeof HomeApplicationsImport
      parentRoute: typeof HomeImport
    }
    '/_home/resume': {
      preLoaderRoute: typeof HomeResumeImport
      parentRoute: typeof HomeImport
    }
    '/_landing/demo': {
      preLoaderRoute: typeof LandingDemoImport
      parentRoute: typeof LandingImport
    }
    '/_landing/pricing': {
      preLoaderRoute: typeof LandingPricingImport
      parentRoute: typeof LandingImport
    }
    '/_landing/': {
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof LandingImport
    }
    '/_home/applications/kanban': {
      preLoaderRoute: typeof HomeApplicationsKanbanImport
      parentRoute: typeof HomeApplicationsImport
    }
    '/_home/applications/table': {
      preLoaderRoute: typeof HomeApplicationsTableImport
      parentRoute: typeof HomeApplicationsImport
    }
    '/_home/resume/$id': {
      preLoaderRoute: typeof HomeResumeIdImport
      parentRoute: typeof HomeResumeImport
    }
    '/_home/jobs/': {
      preLoaderRoute: typeof HomeJobsIndexImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([AuthOnboardRoute]),
  HomeRoute.addChildren([
    HomeAnalyticsRoute,
    HomeApplicationsRoute.addChildren([
      HomeApplicationsKanbanRoute,
      HomeApplicationsTableRoute,
    ]),
    HomeResumeRoute.addChildren([HomeResumeIdRoute]),
    HomeJobsIndexRoute,
  ]),
  LandingRoute.addChildren([
    LandingDemoRoute,
    LandingPricingRoute,
    LandingIndexRoute,
  ]),
  DebugHealthcheckRoute,
])

/* prettier-ignore-end */
